"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class EnrichRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BODY_FIELD_NUMBER: builtins.int
    LANG_FIELD_NUMBER: builtins.int
    body: builtins.str
    lang: builtins.str
    def __init__(
        self,
        *,
        body: builtins.str = ...,
        lang: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["body", b"body", "lang", b"lang"]) -> None: ...

global___EnrichRequest = EnrichRequest

@typing_extensions.final
class Entity(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TEXT_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    SCORE_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    text: builtins.str
    type: builtins.str
    score: builtins.float
    @property
    def index(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        text: builtins.str = ...,
        type: builtins.str = ...,
        score: builtins.float = ...,
        index: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["index", b"index", "score", b"score", "text", b"text", "type", b"type"]) -> None: ...

global___Entity = Entity

@typing_extensions.final
class NLP(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOPWORDS_FIELD_NUMBER: builtins.int
    KEYWORDS_FIELD_NUMBER: builtins.int
    ENTITIES_FIELD_NUMBER: builtins.int
    SUMMARY_FIELD_NUMBER: builtins.int
    TOPICS_FIELD_NUMBER: builtins.int
    CLAIMS_FIELD_NUMBER: builtins.int
    QUOTES_FIELD_NUMBER: builtins.int
    @property
    def stopwords(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def keywords(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def entities(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Entity]: ...
    summary: builtins.str
    @property
    def topics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Entity]: ...
    @property
    def claims(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Entity]: ...
    @property
    def quotes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Entity]: ...
    def __init__(
        self,
        *,
        stopwords: collections.abc.Iterable[builtins.str] | None = ...,
        keywords: collections.abc.Iterable[builtins.str] | None = ...,
        entities: collections.abc.Iterable[global___Entity] | None = ...,
        summary: builtins.str = ...,
        topics: collections.abc.Iterable[global___Entity] | None = ...,
        claims: collections.abc.Iterable[global___Entity] | None = ...,
        quotes: collections.abc.Iterable[global___Entity] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["claims", b"claims", "entities", b"entities", "keywords", b"keywords", "quotes", b"quotes", "stopwords", b"stopwords", "summary", b"summary", "topics", b"topics"]) -> None: ...

global___NLP = NLP

@typing_extensions.final
class Data(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NLP_FIELD_NUMBER: builtins.int
    @property
    def nlp(self) -> global___NLP: ...
    def __init__(
        self,
        *,
        nlp: global___NLP | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["nlp", b"nlp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["nlp", b"nlp"]) -> None: ...

global___Data = Data

@typing_extensions.final
class EnrichResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    status: builtins.str
    """success, error"""
    code: builtins.int
    """200, 500"""
    message: builtins.str
    """message"""
    @property
    def data(self) -> global___Data:
        """data Object {}"""
    def __init__(
        self,
        *,
        status: builtins.str = ...,
        code: builtins.int = ...,
        message: builtins.str = ...,
        data: global___Data | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["data", b"data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["code", b"code", "data", b"data", "message", b"message", "status", b"status"]) -> None: ...

global___EnrichResponse = EnrichResponse
