# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediawatch/passages/v2/passage.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediawatch.common.v2 import common_pb2 as mediawatch_dot_common_dot_v2_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$mediawatch/passages/v2/passage.proto\x12\x16mediawatch.passages.v2\x1a!mediawatch/common/v2/common.proto\"\x82\x01\n\x07Passage\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04text\x18\x02 \x01(\tR\x04text\x12\x1a\n\x08language\x18\x03 \x01(\tR\x08language\x12\x37\n\x04type\x18\x04 \x01(\x0e\x32#.mediawatch.passages.v2.PassageTypeR\x04type\"\x84\x01\n\x0bPassageList\x12\x33\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1f.mediawatch.passages.v2.PassageR\x04\x64\x61ta\x12@\n\npagination\x18\x02 \x01(\x0b\x32 .mediawatch.common.v2.PaginationR\npagination\":\n\x0cQueryPassage\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n\x08language\x18\x03 \x01(\tR\x08language*7\n\x0bPassageType\x12\r\n\tTRIM_LEFT\x10\x00\x12\x0e\n\nTRIM_RIGHT\x10\x01\x12\t\n\x05SPLIT\x10\x02\x32\xc1\x01\n\x0ePassageService\x12S\n\rCreatePassage\x12\x1f.mediawatch.passages.v2.Passage\x1a\x1f.mediawatch.passages.v2.Passage\"\x00\x12Z\n\x0bGetPassages\x12$.mediawatch.passages.v2.QueryPassage\x1a#.mediawatch.passages.v2.PassageList\"\x00\x42\xa4\x01\n\x1a\x63om.mediawatch.passages.v2B\x0cPassageProtoP\x01\xa2\x02\x03MPX\xaa\x02\x16Mediawatch.Passages.V2\xca\x02\x16Mediawatch\\Passages\\V2\xe2\x02\"Mediawatch\\Passages\\V2\\GPBMetadata\xea\x02\x18Mediawatch::Passages::V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mediawatch.passages.v2.passage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.mediawatch.passages.v2B\014PassageProtoP\001\242\002\003MPX\252\002\026Mediawatch.Passages.V2\312\002\026Mediawatch\\Passages\\V2\342\002\"Mediawatch\\Passages\\V2\\GPBMetadata\352\002\030Mediawatch::Passages::V2'
  _globals['_PASSAGETYPE']._serialized_start=427
  _globals['_PASSAGETYPE']._serialized_end=482
  _globals['_PASSAGE']._serialized_start=100
  _globals['_PASSAGE']._serialized_end=230
  _globals['_PASSAGELIST']._serialized_start=233
  _globals['_PASSAGELIST']._serialized_end=365
  _globals['_QUERYPASSAGE']._serialized_start=367
  _globals['_QUERYPASSAGE']._serialized_end=425
  _globals['_PASSAGESERVICE']._serialized_start=485
  _globals['_PASSAGESERVICE']._serialized_end=678
# @@protoc_insertion_point(module_scope)
