"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import mediawatch.common.v2.common_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _PassageType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PassageTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PassageType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TRIM_LEFT: _PassageType.ValueType  # 0
    TRIM_RIGHT: _PassageType.ValueType  # 1
    SPLIT: _PassageType.ValueType  # 2

class PassageType(_PassageType, metaclass=_PassageTypeEnumTypeWrapper): ...

TRIM_LEFT: PassageType.ValueType  # 0
TRIM_RIGHT: PassageType.ValueType  # 1
SPLIT: PassageType.ValueType  # 2
global___PassageType = PassageType

@typing_extensions.final
class Passage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    LANGUAGE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    id: builtins.str
    text: builtins.str
    language: builtins.str
    type: global___PassageType.ValueType
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        text: builtins.str = ...,
        language: builtins.str = ...,
        type: global___PassageType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "language", b"language", "text", b"text", "type", b"type"]) -> None: ...

global___Passage = Passage

@typing_extensions.final
class PassageList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    PAGINATION_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Passage]: ...
    @property
    def pagination(self) -> mediawatch.common.v2.common_pb2.Pagination: ...
    def __init__(
        self,
        *,
        data: collections.abc.Iterable[global___Passage] | None = ...,
        pagination: mediawatch.common.v2.common_pb2.Pagination | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["pagination", b"pagination"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "pagination", b"pagination"]) -> None: ...

global___PassageList = PassageList

@typing_extensions.final
class QueryPassage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    LANGUAGE_FIELD_NUMBER: builtins.int
    id: builtins.str
    language: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        language: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "language", b"language"]) -> None: ...

global___QueryPassage = QueryPassage
