package main

import (
	"context"
	"net/http"
	"net/url"
	"os"
	"os/signal"
	"strconv"
	"syscall"
	"time"

	"github.com/cvcio/mediawatch/models/deprecated/feed"
	"github.com/cvcio/mediawatch/pkg/config"
	"github.com/cvcio/mediawatch/pkg/db"
	"github.com/cvcio/mediawatch/pkg/kafka"
	"github.com/cvcio/mediawatch/pkg/logger"
	"github.com/cvcio/mediawatch/pkg/redis"
	"github.com/cvcio/twitter"
	"github.com/kelseyhightower/envconfig"
	"github.com/pkg/errors"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	kaf "github.com/segmentio/kafka-go"
	"go.uber.org/zap"
)

var FEEDS []string = []string{
	"https://www.sportime.grhttps://www.instagram.com/sportime.gr/feed/?hl=en",
	"https://around.grhttps://around.gr/feed/",
	"https://betone.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fbetone.gr%2F&format=xml",
	"https://evoreia.gr/feed/",
	"https://syrostv1.gr/feed/",
	"https://epirusonline.gr/feed/",
	"https://www.fantazio.gr/feed/",
	"https://dailypost.grhttps://dailypost.gr/feed/",
	"https://www.itsallgreektome.gr/feed/",
	"https://argolida24.gr/feed/",
	"https://statusradio.gr/feed/",
	"https://www.cosmosradio.gr",
	"https://www.elthraki.gr/feed/",
	"https://neaflorina.gr/feed/",
	"https://polydrososparnassou.blogspot.com/feeds/posts/default",
	"https://rethnews.gr/rss.xml",
	"https://www.stereanews.gr/feed/",
	"https://loudias.blogspot.com/feeds/posts/default",
	"https://www.eviazoom.gr/feeds/posts/default",
	"https://www.ilamia.gr/feed/",
	"https://pontos.blogspot.com/feeds/posts/default",
	"https://rodosreport.gr/feed/",
	"https://gnomikilkis.blogspot.com/feeds/posts/default",
	"https://www.kriti24.gr/feed/",
	"https://www.bybus.gr/feed/",
	"https://www.sportaltv.gr/feed/",
	"https://www.periodiko.net/feed/",
	"https://sofokleous10.gr/feed/",
	"https://www.evianext.gr/feed/",
	"https://sportflix.gr/feed/",
	"https://www.imathianews.gr/feeds/posts/default",
	"https://www.aagora.gr/feed/",
	"https://dotradio.gr/?feed=rss2",
	"https://palo.gr/rss/simantikoterarss/",
	"https://www.efsyn.gr/feed.xml",
	"https://www.mikriliga.com/feed/",
	"https://sinidisi.grhttps://feeds.feedburner.com/SinidisiGR",
	"https://salamina.tv/?feed=rss2",
	"https://www.agrotika-nea.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.agrotika-nea.gr%2F&format=xml",
	"https://www.global-communication.gr/feed/",
	"https://flashstars.gr/feed",
	"https://www.flogasport.gr/feed/",
	"https://blife.gr/feed/",
	"https://odialogos.gr/feed/",
	"https://www.life-news.gr/feed/",
	"https://www.protagon.gr/feed",
	"https://agropost.gr/feed/",
	"https://www.megatv.comhttps://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5zaW1wbGVjYXN0LmNvbS9NZm85U0J2Mw?sa=X&ved=0CAIQ9sEGahgKEwio8rKsmN36AhUAAAAAHQAAAAAQqQE",
	"https://www.kathemera.gr/feed/",
	"https://www.efimeridakavala.gr/feed/",
	"https://akritasnews.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fakritasnews.com%2F&format=xml",
	"https://skgnews.gr/feed/",
	"https://motorheads.gr/feed/",
	"https://healthpharma.gr/feed/",
	"https://www.trikalafocus.gr/feed/",
	"https://www.tennis24.gr/feed/",
	"https://enypografa.gr/feed/",
	"https://www.documentonews.gr/feed/",
	"https://www.k-tipos.gr/feed/",
	"https://ipop.gr/feed/",
	"https://www.ptisidiastima.com/feed/",
	"https://athensreviewofbooks.com/?format=feed&type=rss",
	"https://techin.grhttps://www.sofokleousin.gr/feed/",
	"https://www.xploremykonosmagazine.com/feed/",
	"https://focusfm.gr/feed/",
	"https://athenslivenews.gr/?format=feed&type=rss",
	"https://ira1067.gr/feed/",
	"https://greenbusiness.gr/feed/",
	"https://www.lesvosnews.net/rss_feeds",
	"https://ioniantv.gr/feed/",
	"http://kanali6.gr/site/feed/",
	"https://dokari.grhttps://www.dokari.gr/roi-eidiseon?format=feed&type=rss",
	"https://aggelies.larissanet.grhttp://www.larissanet.gr/feed/",
	"https://volvipress.gr/feed/",
	"https://www.kosmoslarissa.gr/rss?projection=1095",
	"https://www.epirusnews.eu/feed/",
	"https://logospellas.gr/feed/",
	"https://www.12vima.gr/feed/",
	"https://dytikielladanews.gr/?feed=rss2",
	"https://www.ploumistos.com/feeds/posts/default",
	"https://palmospress.gr/feed/",
	"https://www.trikalinostypos.gr/feed",
	"https://www.botrini.gr/feed/",
	"https://n-takosnews.gr/feed/",
	"https://politisnews.gr/feed/",
	"https://farkadonaday.gr/feed/",
	"https://thecommonsense.gr/feed/",
	"https://www.skyrodos.gr/feed/",
	"https://sowhat.gr/feed/",
	"https://politisonline.com/feed/",
	"https://www.candiadoc.gr/feed/",
	"https://ecozen.gr/feed/",
	"https://www.thessnews.gr/feed/",
	"https://www.larisanews.gr/feed",
	"https://fonitisparou.gr/?format=feed&type=rss",
	"https://klik.grhttps://www.klik.gr/rss.php",
	"https://youfly.com/feed/",
	"https://greveniotis.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fgreveniotis.gr%2F&format=xml",
	"https://fillinthegap.net/feed/",
	"https://vetonews.gr/?format=feed&type=rss",
	"https://viewsofgreece.gr/feed/",
	"https://iparnassos.gr/feed/",
	"https://live-delta.gr/feed/",
	"https://loudradio.gr/feed/",
	"https://e-bikeit.gr/?format=feed&type=rss",
	"https://menwellada.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fmenwellada.gr%2F&format=xml",
	"https://www.radio984.gr/feed/",
	"https://eboulevard.grhttps://eboulevard.gr/rss.xml",
	"https://www.politismika.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.politismika.gr%2F&format=xml",
	"https://www.kritipress.gr/feed/",
	"https://ebdomi.com/?format=feed&type=rss",
	"https://www.thedots.gr/feed/",
	"https://greekyachtingnews.com/feed/",
	"https://antennafm.gr/?format=feed&type=rss",
	"https://www.familytime.gr/feed/",
	"https://thermansipress.gr/feed/",
	"https://evianews.com/feed/",
	"https://www.paramythia-online.gr/feed/",
	"https://www.travel.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.travel.gr%2F&format=xml",
	"https://energyup.gr/feed/",
	"https://www.kozanilife.gr/feed/",
	"https://city24.gr/feed/",
	"https://www.airetos.gr/rss.aspx",
	"https://thessalikos.gr/feed/",
	"https://perpetual.gr/feed/",
	"https://www.rthess.gr/feed/",
	"https://www.kalamatatimes.gr/feed/",
	"https://sofokleousin.grhttps://www.sofokleousin.gr/feed/",
	"https://www.tameteora.gr/feed/",
	"https://www.trikalavoice.gr/feed/",
	"https://www.roinews.gr/feed/",
	"https://www.nafpaktosvoice.gr/feed/",
	"https://psithiri.gr/feed/",
	"https://mouzakinews.gr/feed/",
	"https://www.palmosev.gr/feed/",
	"https://www.kalimera-ellada.gr/feed/",
	"https://laconialive.gr/feed/",
	"https://athnews.gr/home/feed/",
	"https://doma.archi/feed/",
	"https://basketworld.net/feed/",
	"https://cosmosnews.gr/feed/",
	"https://istorika.gr/?format=feed&type=rss",
	"https://www.gossiplive.eu/feeds/posts/default",
	"https://www.real.gr/rss8.asp?catid=42767&subid=20120",
	"https://www.libre.gr/feed/",
	"https://www.boatfishing.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.boatfishing.gr%2F&format=xml",
	"https://vdmedia.gr/feed/",
	"https://centertv.gr/feed",
	"https://www.larisacitynews.gr/feeds/posts/default",
	"https://entospolis.gr/feed/",
	"https://hellenicmediagroup.com/feed/",
	"https://naxostimes.gr/feed/",
	"https://www.gossipstory.gr/feed/",
	"https://lakonikostypos.gr/?format=feed&type=rss",
	"https://orizontespress.gr/feed/",
	"https://ictplus.gr/feed/",
	"https://entheto.gr/feed/",
	"https://www.restarttourism.gr/feed/",
	"https://samosvoice.gr/feed/",
	"https://www.newmoney.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.newmoney.gr%2F&format=xml",
	"https://www.taxydromos.gr/feed/home",
	"https://www.limnosreport.gr/feed/",
	"https://top-sport.gr/index.php?format=feed&type=rss",
	"https://www.beautetinkyriaki.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.beautetinkyriaki.gr%2F&format=xml",
	"https://www.onecon.gr/?feed=rss2",
	"https://ermisilias.gr/index.php?format=feed&type=rss",
	"https://medicalcongress.gr/feed/",
	"https://www.karfitsa.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.karfitsa.gr%2F&format=xml",
	"https://humansofkalamata.gr/feed/",
	"https://ota365.gr/feed/",
	"https://radar.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fradar.gr%2F&format=xml",
	"https://polispost.com/feed/",
	"https://maroussiparatiritirio.blogspot.com/feeds/posts/default",
	"https://www.mesogeiostv.gr/feed/",
	"https://www.enikos.gr/feed/",
	"https://www.thrakikiagora.gr/feed",
	"https://epikairotita.info/index.php?format=feed&type=rss",
	"https://www.kalliergo.gr/feed/",
	"https://www.businessnews.gr/?format=feed",
	"https://protinewskorinthias.gr/feed/",
	"https://www.perifereiaka.gr/feeds/posts/default",
	"https://www.onairnews.gr/?feed=rss2",
	"https://ergasia-press.gr/feed/",
	"https://stonisi.grhttps://feeds.feedburner.com/stonisigr",
	"https://xirafi.gr/feed/",
	"https://tolminews.gr/feed/",
	"https://travel.eleftheriaonline.gr/?format=feed&type=rss",
	"https://www.greekschannel.com/gr/rss/latest-articles/",
	"https://www.novasports.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.novasports.gr%2F&format=xml",
	"https://beerandbar.gr/feed/",
	"https://www.peristerinews.gr/feed/",
	"https://bookpress.gr/?format=feed&type=rss",
	"https://runnermagazine.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Frunnermagazine.gr%2F&format=xml",
	"https://alphapatras.gr/feed/",
	"https://www.neakriti.gr/rss",
	"https://www.slide.gr/feed/",
	"https://moneyview.gr/feed/",
	"https://arenalarissa.gr/feed/",
	"https://www.queen.grhttps://www.queen.gr/latest?format=feed",
	"https://efkozani.gr/feed/",
	"https://www.lamiareport.gr/index.php/roi?format=feed&type=rss",
	"https://www.ekklisiaonline.gr/feed/",
	"https://www.evia24ores.gr/feeds/posts/default",
	"https://todaypress.gr/feed/",
	"https://allaboutaris.gr/feed/",
	"https://energymag.gr/news/feed/",
	"https://groovystation.gr/feed/",
	"https://portoni.gr/feed/",
	"https://typosepeirou.gr/?feed=rss2&page_id=153",
	"https://menidiatis.blogspot.com/feeds/posts/default",
	"https://eurozoi.gr/feed/",
	"https://www.e-gortynia.gr/feed/",
	"https://www.kavala-portal.gr/feed/",
	"https://serres24.gr/feed/",
	"https://www.kerkidasport.gr/?format=feed&type=rss",
	"https://healthup.gr/feed/",
	"https://www.thepresident.gr/feed/",
	"https://socialpolicy.gr/feed",
	"https://www.kalimera-arkadia.gr/?format=feed&type=rss",
	"https://neosagon.gr/feed/",
	"https://kifissiacity.gr/feed/",
	"https://katerinisport.gr/?feed=rss2",
	"https://hotelmag.grhttps://hotelmag.gr/category/tourismos/feed/",
	"https://prismaradio.gr/feed/",
	"https://eordaialive.com/feed/",
	"https://newsopen.gr/feed/",
	"https://workenter.gr/feed/",
	"https://www.agiaparaskevi-guide.gr/feeds/posts/default",
	"https://argolidafm.gr/feed/",
	"https://www.samos24.gr/feed/",
	"https://ekefalonia.gr/feed/",
	"https://erotokritos.gr/feed/",
	"https://zografounews.gr/feed/",
	"https://enalionoffshore.gr/feed/",
	"https://www.dogma.gr/feed/",
	"https://www.alerttv.com.gr/feed/",
	"https://evdomimera.gr/feed/",
	"https://takisonair.gr/feed/",
	"https://24oresimathia.gr/index.php?format=feed&type=rss",
	"https://xanthi2.gr/feed/",
	"https://play-news.gr/feed/",
	"https://advertising.gr/pages/rss.aspx",
	"https://live-oraiokastro.gr/feed/",
	"https://onprevezanews.gr/feed/",
	"https://www.inkefalonia.gr/?format=feed&type=rss",
	"https://magnesianews.gr/feed",
	"https://irunmag.gr/feed/",
	"https://www.liberal.gr/news-feed/20221208",
	"https://olanea.gr/feed/",
	"https://www.sportime24.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.sportime24.gr%2F&format=xml",
	"https://www.euro2day.gr/rss.ashx?chiid=899001",
	"https://dytikanea.gr/feed/",
	"https://www.mediapress.gr/feed/",
	"https://www.symboulos.gr/feed/",
	"https://odigos.biz/feed/",
	"https://atticaonline.gr/feed/",
	"https://amfissapress.gr/feed/",
	"https://thessalonygeia.gr/feed/",
	"https://paratiritis-artas.gr/index.php?format=feed&type=rss",
	"https://zarparadio.gr",
	"https://protiekdosi.news/feed/",
	"https://filodimos.gr/?format=feed&type=rss",
	"https://kalymnos-news.gr/feed/",
	"https://agrafto.gr/rss_feeds.php",
	"https://focustonevro.gr/feed/",
	"https://gr.hellomagazine.com/feed",
	"https://www.rythmos1019.gr/feed/",
	"https://www.proinos-typos.gr/feed/",
	"https://onradio.gr/feed/",
	"https://aetos-grevena.blogspot.com/feeds/posts/default",
	"https://www.vimanews.gr/feed/",
	"https://www.moved.gr/feed/",
	"https://zwnews.gr/feed/",
	"https://insomnia.grhttps://www.insomnia.gr/profile/220897-zergoulini/?tab=node_feedback_Feedback",
	"https://ireporterworld.com/feed/",
	"https://www.laikoyra.gr/feeds/posts/default",
	"https://exploringgreece.tv/feed/",
	"https://www.dromosfm.gr/feed/",
	"https://www.amorgos-news.gr/feed/",
	"https://www.fosonline.gr/news?format=feed&type=rss",
	"https://www.lamianews.gr/feed/",
	"https://paidis.com/feed/",
	"https://tetartopress.gr/feed/",
	"https://oroposnews.com/feed/",
	"https://vpgroupnet.com/feed",
	"https://marousi24.gr/feed/",
	"https://dimarxe.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fdimarxe.gr%2F&format=xml",
	"https://neoi-kairoi.gr/feed/",
	"https://www.protothema.grhttps://www.protothema.gr/rss",
	"https://naousanews.gr/index.php?format=feed&type=rss",
	"https://paopantou.gr/feed/",
	"https://www.lesvospen.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.lesvospen.gr%2F&format=xml",
	"https://ermisnews.gr/feed/",
	"https://www.verrosike.gr/feed/",
	"https://www.xtypos.gr/feed/",
	"https://wsl.gr/feed/",
	"https://www.aigialeia24.gr/feed/",
	"https://www.greeknews24.gr/feed/",
	"https://www.lamiafm1.gr/feed/",
	"https://www.visitpreveza.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.visitpreveza.gr%2F&format=xml",
	"https://aptaliko.gr/?format=feed&type=rss",
	"https://www.enanews.gr/feed/",
	"https://athinorama.gr/newsfeed?page=2",
	"https://kalitheapress.gr/feed/",
	"https://truestory.gr/feed/",
	"https://www.shape.gr/newsfeed?page=2&iscroll=1",
	"https://opolitis.gr/feed/",
	"https://pireastime.gr/?format=feed&type=rss",
	"https://15minutes.gr/feed/",
	"https://www.texnikos.gr/feed",
	"https://thesstoday.gr/feed/",
	"https://xploremykonosnews.gr/feed/",
	"https://ekorinthos.gr/feed/",
	"https://www.e-mastoras.com/feed/",
	"https://any-news.gr/feed/",
	"https://spercheiosbridge.blogspot.com/feeds/posts/default",
	"https://paralympicus.gr/feed/",
	"https://www.megaratv.gr/feed/",
	"https://www.missbloom.gr/newsfeed?page=2&iscroll=1",
	"https://halkidikifocus.gr/focus/index.php?format=feed&type=rss",
	"https://www.ot.grhttps://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5zaW1wbGVjYXN0LmNvbS9UQ0Q2ZHE1Sw",
	"https://www.lykavitos.gr/newsfeed",
	"https://anex.gr/feed/",
	"https://epiloges.tv/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fepiloges.tv%2F&format=xml",
	"https://expertnews.gr/feed/",
	"https://xrisima.gr/feed/",
	"https://diastixo.gr/rss",
	"https://www.motorone.gr/feed/",
	"https://www.youtube.com/feeds/videos.xml?channel_id=UCdIboxAt_EpphCRuivPoX1Q",
	"https://musicaradio.grhttps://www.musicaradio.gr/feed/",
	"https://omorfataxidia.gr/feed/",
	"https://www.filadelfia-xalkidona.gr/feed/",
	"https://www.evros-news.gr/feed/",
	"https://www.rousfm.com/feed/",
	"https://peripteron.eu/feed/",
	"https://www.htpress.gr/feed/",
	"https://athina984.gr/feed/",
	"https://www.ellinikigeorgia.gr/feed/",
	"https://akx.grhttps://www.akx.gr/feed/",
	"https://ilia.news/feed/",
	"https://zantereport.gr/feed/",
	"https://ipolimas.gr/index.php?format=feed&type=rss",
	"https://mycity.gr/feed/",
	"https://www.argolikeseidhseis.gr/feeds/posts/default",
	"https://www.matrix24.gr/matrix24-homepage-2/feed/",
	"https://www.orthodoxtimes.gr/feed/",
	"https://www.radioevros.gr/feed/",
	"https://nrgmusic.gr/feed/",
	"https://astinomiko.gr/feed/",
	"https://www.faros-24.gr/feeds/posts/default",
	"https://www.vox1033.gr/feed/",
	"https://www.palmoskalymnou.gr/feed/",
	"https://grandsport.gr/feed/",
	"https://energyfeed.gr/?feed=rss2",
	"https://virus.com.gr/feed/",
	"https://insuranceworld.gr/feed/",
	"https://www.samiakonvima.gr/feeds/posts/default",
	"https://sportfmpatras.gr/feed/",
	"https://messiniapress.gr/feed/",
	"https://www.notiareport.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.notiareport.gr%2F&format=xml",
	"https://techblog.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Ftechblog.gr%2F&format=xml",
	"https://www.votanistas.com/feed/",
	"https://mavrosgatos.gr/feed/",
	"https://www.serrespost.gr/feed/",
	"https://drive.gr/rss",
	"https://www.automotopatras.gr/feed/",
	"https://www.bankingnews.grhttps://www.bankingnews.gr/rss",
	"https://radio-lehovo.gr/feed/",
	"https://www.dznews.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.dznews.gr%2F&format=xml",
	"https://patranews.gr/feed/",
	"https://www.onmed.gr/rss",
	"https://www.serressport.gr/feed/",
	"https://www.ogdoo.gr/?format=feed&type=rss",
	"https://koinoniki.gr/feed/",
	"https://thessi.grhttps://validator.w3.org/feed/check.cgi?url=https%3A//www.thessi.gr/rss",
	"https://www.onlydriving.gr/feed/",
	"https://www.anoixifm.gr/index.php/feed/",
	"https://destanea.com/?format=feed&type=rss",
	"https://titormosnet.gr/feed/",
	"https://defencereview.gr/feed/",
	"https://www.3good.gr/feed/",
	"https://inpaok.com/feed/",
	"https://winetrails.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwinetrails.gr%2F&format=xml",
	"https://www.mynews.gr/feed/",
	"https://www.paok24.com/feed/",
	"https://www.thessalonikiguide.gr/feed/",
	"https://agrosymbol.gr/feed/",
	"https://avgi.gr/rss.xml",
	"https://www.orafok.gr/feed/",
	"https://infoserres.com/?feed=rss2",
	"https://www.irafina.gr/feed/",
	"https://tetrapodo.gr/?format=feed&type=rss",
	"https://www.avgi.gr/rss.xml",
	"https://www.political.gr/feed/",
	"https://molonoti.gr/rss.xml",
	"https://ekalpi.gr/feed/",
	"https://www.oichalianews.gr/index.php/rss.xml",
	"https://stonenews.eu/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fstonenews.eu%2F&format=xml",
	"https://techit.gr/feed/",
	"https://www.zappit.gr/feed",
	"https://limnosxpress.gr/feed/",
	"https://meaculpa.gr/feed/",
	"https://www.thessaliavoice.gr/feed/",
	"https://mypressnet.gr/feed/",
	"https://diafaneia.eu/feed/",
	"https://digitalcultureplus.com/?feed=rss2",
	"https://www.skai.gr/newsfeed",
	"https://taneamas.gr/?feed=rss2",
	"https://mpetskas.com/?feed=rss2",
	"https://arthro.gr/feed/",
	"https://www.e-west.gr/feed/",
	"https://www.vivanews.gr/feed/",
	"https://www.onalert.grhttps://twitter.com/OnAlertfeed",
	"https://gegonota.news/feed/",
	"https://liveit.gr/feed/",
	"https://xanthipost.gr/feed/",
	"https://insuranceforum.gr/feed/",
	"https://neatisviotias.gr/?feed=rss2",
	"https://lefkadapress.gr/feed/",
	"https://politic.gr/feed/",
	"https://www.terramag.gr/feed/",
	"https://fimotro.gr/feed/",
	"https://www.chiospen.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.chiospen.gr%2F&format=xml",
	"https://www.aparaskevi-images.gr/feed/",
	"https://www.patris.gr/feed/",
	"https://www.radioparatiritis.gr/feed/",
	"https://i247.gr/feed/",
	"https://eproodos.gr/feed",
	"https://kourdistoportocali.com/feed/",
	"https://itnnews.gr/feed/",
	"https://thesseconomy.gr/feed/",
	"https://975fm.gr/feed/",
	"https://www.tvopen.grhttps://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy83ZGJmYWM1Yy9wb2RjYXN0L3Jzcw?sa=X&ved=2ahUKEwjYnIPe3uH6AhWQn_0HHUtFDYUQ9sEGegQIARAC",
	"https://www.hoteldesign.gr/feed/",
	"https://kinitanea.gr/feed/",
	"https://www.veriotises.gr/feed/",
	"https://ppparou.blogspot.com/feeds/posts/default",
	"https://travelmagic.gr/feed/",
	"https://www.anatropinews.gr/feed/",
	"https://xronos-kozanis.gr/feed/",
	"https://business4sdgs.gr/feed/",
	"https://taepikaira.gr/feed/",
	"https://argolikianaptiksi.gr/feed/",
	"https://aitoliavoice.gr/feed/",
	"https://paraktios.gr/feed/",
	"https://proinosmorias.gr/feed/",
	"https://ploumistofylakto.gr/feed/",
	"https://tinealarissa.gr/feed/",
	"https://eleftherostypos.gr/feed",
	"https://larissatoday.gr/feed/",
	"https://karousosartcritics.blogspot.com/feeds/posts/default",
	"https://www.iatropedia.gr/feed/",
	"https://thessports.gr/feed/",
	"https://www.pirgiotis.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.pirgiotis.gr%2F&format=xml",
	"https://iporta.gr/feed/",
	"https://maronnews.gr/feed/",
	"https://www.leonidion.gr/feeds/posts/default",
	"https://corfutvnews.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fcorfutvnews.gr%2F&format=xml",
	"https://www.radiopolis.gr/feed/",
	"https://kontasou.com/feed/",
	"https://www.epirusnow.gr/feed/",
	"https://healthstories.gr/feed/",
	"https://iliavoice.gr/feed/",
	"https://www.fonitisxanthis.gr/feed/",
	"https://www.coffeemag.gr/feed/",
	"https://www.kritikosfm.gr/feeds/posts/default",
	"https://www.madeingreece.news/feed",
	"https://hania.news/feed/",
	"https://ecopress.gr/feed/",
	"https://netnews.gr/feed/",
	"https://www.rodostoday.gr/feed/",
	"https://epikairotitanews.gr/?format=feed&type=rss",
	"https://www.trikalaonline.gr/feed/",
	"https://live-kilkis.gr/feed/",
	"https://evrytanika.gr/feed/",
	"https://stotapsi.gr/?format=feed&type=rss",
	"https://vimakritis.gr/feed/",
	"https://serresnow.gr/feed/",
	"https://www.kykladiki.gr/feed/",
	"https://fonirodopis.gr/press/feed/",
	"https://www.kentrikiellada.gr/feed/",
	"https://www.newsbomb.gr/oles-oi-eidhseis?format=feed&type=rss",
	"https://www.agrinioculture.gr/feed/",
	"https://athlitiko.gr/wp-json/oembed/1.0/embed?url&format=xml",
	"https://www.melodiapatras.gr/site/feed/",
	"https://ptolemaida.tv/index.php?format=feed&type=rss",
	"https://www.kalavrytapress.gr/feed/",
	"https://aeolos.tv/feed/",
	"https://childit.gr/feed/",
	"https://kalymnosnow.gr/index.php/roi-eidiseon?format=feed&type=rss",
	"https://boro.gr/feed/",
	"https://www.alpha-news.gr/feed/",
	"https://patravoice.gr/feed/",
	"https://socialmedialife.grhttp://feeds.feedburner.com/smlifegr",
	"https://www.piperatanews.gr/feed/",
	"https://fnl-guide.comhttps://www.fnl-guide.com/rss.php",
	"https://nonstopnews.gr/?format=feed&type=rss",
	"https://olympiobima.gr/feed/",
	"https://proinoslogosnews.gr/feed/",
	"https://tilegrafimanews.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Ftilegrafimanews.gr%2F&format=xml",
	"https://ypodomes.com/feed/",
	"https://terranews.gr/?format=feed&type=rss",
	"https://youlike.gr/feed/",
	"https://www.cretangastronomy.gr/feed/",
	"https://www.oneman.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.oneman.gr%2F&format=xml",
	"https://lamianow.gr/feed/",
	"https://www.thraki.com.gr/feed/",
	"https://empros.gr/feed/",
	"https://pelop.gr/feed/",
	"https://menoumeholargo.gr/feed/",
	"https://erevnapress.eu/feed/",
	"https://loveradio882.gr/feed/",
	"https://www.agronews.grhttps://www.agronews.gr/rss",
	"https://www.ygeiologia.gr/feed/",
	"https://parnesnews.gr/feed/",
	"https://www.larisanew.gr/feed/",
	"https://grdiscovery.com/feed/",
	"https://www.asfalisinet.gr/feed/",
	"https://blog.moudaniwn.gr/feed/",
	"https://www.auto-moto-news.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.auto-moto-news.gr%2F&format=xml",
	"https://antinews.gr/feed/",
	"https://www.sportstonoto.gr/feed/",
	"https://www.fineview.gr/feed/",
	"https://www.kathimerini.grhttps://feeds.feedburner.com/kathimerini/DJpy",
	"https://menta88.gr/feed/",
	"https://www.tvsmile.gr/feed/",
	"https://www.reporterkallitheas.gr/feed/",
	"https://www.eroticos.gr/feed",
	"https://fonografos.net/feed/",
	"https://www.vwoman.gr/feed/",
	"https://healthmag.gr/feed/",
	"https://www.thebest.grhttps://www.thebest.gr/feed",
	"https://www.goal12.gr/feed/",
	"https://itraveltogreece.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fitraveltogreece.com%2F&format=xml",
	"https://chiosshops.gr/?feed=rss2",
	"https://www.imerisia-ver.gr/feed/rss",
	"https://www.naftemporiki.gr/feed/",
	"https://www.patriotes.gr/feed/",
	"https://worldenergynews.grhttps://www.worldenergynews.gr/rss",
	"https://www.kontranews.gr/feed/",
	"https://protionline.gr/feed/",
	"https://www.travelstyle.gr/feed/",
	"https://www.cretadrive.gr/feed",
	"https://www.amhenews.gr/feed/",
	"https://sayyestothepress.gr/feed/",
	"https://foreignnews.gr/feed/",
	"https://www.militaire.gr/feed/",
	"https://fonikastorias.gr/feed/",
	"https://www.artabest.gr/feed/",
	"https://foreignaffairs.gr/rss.xml",
	"https://www.karditsanews.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.karditsanews.gr%2F&format=xml",
	"https://planetwebradio.gr/feed/",
	"https://kavalawebnews.gr/feed/",
	"https://www.toxrima.gr/feed/",
	"https://www.lesvospost.com/feeds/posts/default",
	"https://www.evialead.gr/?feed=rss2",
	"https://www.ionianet.gr/feed/",
	"https://www.astra992.gr/feed/",
	"https://www.circogreco.gr/feed/",
	"https://daysofart.gr/feed/",
	"https://www.editorial.gr/feed/",
	"https://pagkaki.gr/index.php?format=feed&type=rss",
	"https://arta2day.gr/feed/",
	"https://www.aftodioikisi.gr/feed/",
	"https://www.party971.gr/feed/",
	"https://www.bestfm1031.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.bestfm1031.gr%2F&format=xml",
	"https://www.e-folegandros.gr/feed/",
	"https://foroline.gr/feed",
	"https://news.b2green.gr/feed",
	"https://www.veriotis.gr/feeds/posts/default",
	"https://lesvosdays.gr/feed/",
	"https://www.skolarikos.gr/feed/",
	"https://www.astratv.gr/feed/",
	"https://travelpreveza.gr/feed/",
	"https://kalamatain.gr/new/feed/",
	"https://energyworld.gr/feed/",
	"https://www.polismedia.gr/feed/",
	"https://www.nou-pou.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.nou-pou.gr%2F&format=xml",
	"https://www.agro24.gr/rss.xml",
	"https://www.daynight.gr/feed/",
	"https://www.gargalianoionline.gr/feed/",
	"https://www.ilianet.gr/feed/",
	"https://tvreporters.gr/feed/",
	"https://www.cocktail89tirnavos.gr/feed/",
	"https://www.star-fm.gr/feed/",
	"https://autoelectricnews.gr/feed/",
	"https://www.history-point.gr/feed",
	"https://axarnea.gr/feed/",
	"https://messinianews.gr/feed/",
	"https://oladeka.com/feed/",
	"https://caranddriver.grhttps://www.caranddriver.gr/eidiseis/rss/",
	"https://inthess.gr/feed/",
	"https://www.neoiorizontes.gr/feed/",
	"https://myphone.gr/feed/",
	"https://www.mama365.grhttps://www.mama365.gr/rss.ashx",
	"https://portnet.gr/?format=feed&type=rss",
	"https://newdoc.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fnewdoc.gr%2F&format=xml",
	"https://kaipoutheos.gr/feed",
	"https://www.olivenews.gr/el/feed/",
	"https://www.3kalanews.gr/feed/",
	"https://iqbeaute.com/feed/",
	"https://www.tokarfi.gr/feed/",
	"https://info-war.gr/feed/",
	"https://penna.gr/?format=feed&type=rss",
	"https://limnosfm100.gr/?format=feed&type=rss",
	"https://magdasnews.gr/feed/",
	"https://www.news.gr/rss.ashx",
	"https://yabatravellers.com/feed/",
	"https://allyou.gr/?format=feed&type=rss",
	"https://mad.tv/feed/",
	"https://www.messinialive.gr/feed/",
	"https://pella24.gr/rss.xml",
	"https://www.kavalapoint.gr/feed/",
	"https://eviaone.gr/feed/",
	"https://ifarsala.grhttps://www.ifarsala.gr/feed",
	"https://newse.gr/feed/",
	"https://stoxos1049.gr/feed",
	"https://www.goalpost.gr/feed",
	"https://www.idanikospiti.gr/feed/",
	"https://gefira.gr/feed/",
	"https://kallitheaonline.gr/index.php?format=feed&type=rss",
	"https://www.pressbomb.gr/feeds/posts/default",
	"https://www.argolidamagazine.gr/feeds/posts/default",
	"https://thessalikipress.gr/feed/",
	"https://www.eidisis.gr/feed/rss/",
	"https://kefalonianmantata.gr/feed/",
	"https://sentra.com.gr/feed/",
	"https://stocklearning.gr/rss.aspx",
	"https://www.sportsioannina.gr/feed/",
	"https://poimin.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fpoimin.gr%2F&format=xml",
	"https://www.pakoe.gr/feed/",
	"https://www.securitymanager.gr/feed/",
	"https://cityrider.gr/?format=feed&type=rss",
	"https://flnews.gr/?format=feed&type=rss",
	"https://www.media.gr/feed/",
	"https://tastv.gr/rss.xml",
	"https://patrasvoice.com/feed/",
	"https://lamia365.gr/feed/",
	"https://neaait.gr/feed/",
	"https://radioamfissa.gr/feed/",
	"https://www.michanikos-online.gr/feed/",
	"https://www.aspropyrgosnews.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.aspropyrgosnews.gr%2F&format=xml",
	"https://www.lihnarifm.gr/feed/",
	"https://www.astrology.grhttp://feeds.feedburner.com/Astrologygr",
	"https://www.infocom.gr/feed/",
	"https://xanthinews.gr/feed/",
	"https://www.athens-art.gr/feed/",
	"https://www.palmos-glyfada.gr/index.php?rest_route=%2Foembed%2F1.0%2Fembed&url=https%3A%2F%2Fwww.palmos-glyfada.gr%2F&format=xml",
	"https://www.thenewspaper.gr/feed/",
	"https://news2u.gr/rss.xml",
	"https://www.dimokratiki.gr/feed/",
	"https://kidiesnews.gr/feed/",
	"https://www.xolargos-papagou.gr/feed/",
	"https://maroussi-news.gr/feed/",
	"https://enachannel.gr/feed/",
	"https://nautilia.gr/feed/",
	"https://seleo.gr/feed/",
	"https://www.daddy-cool.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.daddy-cool.gr%2F&format=xml",
	"https://xmaslife.gr/feed/",
	"https://politicalbank.gr/feed/",
	"https://www.defence-point.gr/news/feed",
	"https://supertvkorinthos.gr/?format=feed",
	"https://www.inevros.gr/feed/",
	"https://www.pierianews.gr/feed/",
	"https://www.radiokalloni.gr/feed",
	"https://egnatia.tvhttps://egnatia.tv/rss.xml",
	"https://elculture.gr/feed/",
	"https://serresmegasport.gr/feed/",
	"https://activeman.gr/feed/",
	"https://www.alexandreia-gidas.gr/2017/feed/",
	"https://ontime24.gr/feed/",
	"https://www.almyros.gr/feed/",
	"https://emvolos.gr/feed/",
	"https://34100tv.com/feed/",
	"https://www.yupiii.gr/newsfeed",
	"https://www.pliroforiodotis.gr/index.php?format=feed&type=rss",
	"https://www.evrytanikospalmos.gr/feed/",
	"https://pressgreece.gr/feed/",
	"https://www.kerkyrasimera.gr/feed/",
	"https://www.alexpolisonline.com/feeds/posts/default",
	"https://thrakionline.gr/?feed=rss2",
	"https://www.iloveithaki.gr/feed/",
	"https://carselectric.gr/feed/",
	"https://www.copywrite.gr/feed/",
	"https://timeline.gr/feed/",
	"https://sifnaiko-fos.gr/feed/",
	"https://www.larisaevents.gr/feed/",
	"https://www.thessalikesepiloges.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.thessalikesepiloges.gr%2Farxikh%2F&format=xml",
	"https://wearemedia.gr/feed/",
	"https://www.infokids.cy/feed/",
	"https://parostourguide.com/?feed=rss2",
	"https://piraeuspress.gr/feed/",
	"https://aek365.orghttps://feeds.feedburner.com/aek365gr-aek",
	"https://exofyllo.gr/feed/",
	"https://nplconfidential.com/feed/",
	"https://apopseis.gr/feed/",
	"https://politeianews.gr/feed/",
	"https://focus-radio.gr/feed/",
	"https://smilefamily.gr/feed/",
	"https://womensnews.gr/feed/",
	"https://www.aboutgreece.gr/feed/",
	"https://rafinatanews.gr/index.php?format=feed&type=rss",
	"https://e-mesara.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fe-mesara.gr%2F&format=xml",
	"https://lagadaspress.gr/news/feed/",
	"https://chaniamagazine.gr/feed/",
	"https://oknews.gr/feed/",
	"https://aitoloakarnaniabest.grhttp://feeds.feedburner.com/AitoloakarnaniaBest",
	"https://mamamia.gr/component/fpss/module/106?format=feed&type=rss",
	"https://www.hlektra.gr/feed/",
	"https://www.imerazante.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.imerazante.gr%2F&format=xml",
	"https://texnikoskosmos.gr/feed/",
	"https://www.lavart.gr/feed/",
	"https://www.dikaiologitika.grhttps://feeds.feedburner.com/dikaiologitika/ZteV",
	"https://paixnidaki.com/feed/",
	"https://enimerosou.gr/feed/",
	"https://www.blackmonday.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.blackmonday.gr%2F&format=xml",
	"https://deltatv.gr/feed/",
	"https://blueskytv.gr/feed/",
	"https://www.voreiaproastia.gr/feed/",
	"https://agriniovoice.gr/feed/",
	"https://www.xanthinea.gr/feeds/posts/default",
	"https://marousiotiko.gr/feed/",
	"https://prevezabest.blogspot.com/feeds/posts/default",
	"https://www.newsmag.gr/feed/",
	"https://www.bloko.gr/feeds/posts/default",
	"https://petpet.news/feed/",
	"https://www.tlife.gr/feed/",
	"https://eviathema.gr/feed/",
	"https://glife.gr/feed/",
	"https://atlantea.news/feed/",
	"https://www.drdoctor.doctor/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.drdoctor.doctor%2Farxikh%2F&format=xml",
	"https://koinsep.org/feed/",
	"https://eptanews.gr/feed/",
	"https://matchnews.gr/feed/",
	"https://greenagenda.gr/feed/",
	"https://www.agriniotimes.grhttps://feeds.feedburner.com/feed/AgrinioTimes",
	"https://www.kefaloniapress.gr/feed/",
	"https://trikalaculture.gr/feed/",
	"https://elxate.gr/feed/",
	"https://amarysia.gr/feed",
	"https://sportsaddict.gr/feed/",
	"https://www.eleftheria.gr/?format=feed&type=rss",
	"https://www.powergame.gr/feed/",
	"https://maroussi.city/feed/",
	"https://diefxon.com/feed/",
	"https://safety.hellenicmediagroup.com/?feed=rss2",
	"https://www.adesmeuti.gr/feed/",
	"https://www.ikariaki.gr/feed/",
	"https://kozani.tv/index.php?format=feed&type=rss",
	"https://www.energypost.gr/feed/",
	"https://lesvosvoice.gr/feed/",
	"https://runnfun.gr/feed/",
	"https://www.zarpanews.gr/feed/",
	"https://live-thessaloniki.gr/feed/",
	"https://tovimatisaigialeias.gr/?format=feed&type=rss",
	"https://www.report24.gr/feed/",
	"https://www.parapolitika.grhttps://parapolitika.gr/rss",
	"https://basketa.gr/feed/",
	"https://anepikairos.gr/?format=feed&type=rss",
	"https://thessalonomorfia.gr/feed/",
	"https://www.theonlinepress.gr/?feed=rss2",
	"https://www.almopia24.gr/feeds/posts/default",
	"https://www.newsbreak.gr/feed/",
	"https://www.androsportal.gr/feed/",
	"https://medicalnews.gr/feed/",
	"https://republicradio.gr/feed/",
	"https://cycladeslive.gr/feed/",
	"https://arenanews.gr/feed/",
	"https://www.koumanto.gr/feed/",
	"https://www.livezone.gr/feed/",
	"https://thesnea24.gr/home/feed/",
	"https://aigaiolive.gr/feed/",
	"https://www.healthreportaz.gr/feed/",
	"https://thesocialist.gr/feed/",
	"https://3vita.gr/feed",
	"https://goal-trikala.gr/feed/",
	"https://giafkasports.gr/?format=feed&type=rss",
	"https://booksjournal.gr/?format=feed&type=rss",
	"https://taxianddriver.gr/feed/",
	"https://www.shippingtv.gr/feed/",
	"https://xionodromika.gr/feed/",
	"https://best-tv.gr/feed/",
	"https://www.npress.gr/feed/",
	"https://www.politispress.gr/feed/",
	"https://www.karatzova.com/feeds/posts/default",
	"https://www.enadeals.gr/feed/",
	"https://pieriasocial.gr/?feed=rss2",
	"https://www.koutipandoras.gr/feed/",
	"https://ebasket.gr/feed",
	"https://www.haniotika-nea.gr/feed/",
	"https://kastoria.news/feed/",
	"https://viotianet.gr/feed",
	"https://taneatisthrakis.blogspot.com/feeds/posts/default",
	"https://www.protinews.com.gr/feed/",
	"https://www.biscotto.gr/rest_api/oembed/1.0/embed?url=https%3A%2F%2Fwww.biscotto.gr%2F&format=xml",
	"https://mice.gr/feed/",
	"https://www.ecoearth.gr/feed/",
	"https://westnews.gr/feed/",
	"https://krnews.gr/feed/",
	"https://valuenews.gr/feed",
	"https://radioalexandros.com/index.php?format=feed&type=rss",
	"https://www.avopolis.gr/?format=feed&type=rss",
	"https://thefaq.gr/feed/",
	"https://www.drt915.gr/feed/",
	"https://www.agriniosite.gr/feed/",
	"https://www.thestival.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.thestival.gr%2F&format=xml",
	"https://klife.gr/feed/",
	"https://www.vimaorthodoxias.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.vimaorthodoxias.gr%2F&format=xml",
	"https://iaitoloakarnania.gr/feed/",
	"https://www.appsradio.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.appsradio.gr%2F&format=xml",
	"https://www.greenattica.gr/feed/",
	"https://fonitisydras.com/newsfeed",
	"https://viotia.blogspot.com/feeds/posts/default",
	"https://amfissanewz.blogspot.com/feeds/posts/default",
	"https://www.infowoman.gr/feed/",
	"https://startupper.gr/feed/",
	"https://arouraios.gr/feed/",
	"https://northdoctors.gr/feed/",
	"https://toxotisfm.gr/feed/",
	"https://www.net-time.gr/feed/",
	"https://www.autonomous.gr/feed/",
	"https://medicalmanage.gr/?format=feed&type=rss",
	"https://www.proinanea.gr/feed/",
	"https://palmospatras.gr/feed/",
	"https://www.aixminews.gr/index.php/feed/",
	"https://meatnews.gr/feed/",
	"https://argolida24news.gr/feed/",
	"https://kidshub.gr/feed/",
	"https://tozizanio.gr/feed/",
	"https://atticacoast.gr/atticacoast/feed/",
	"https://www.foni-visaltias.gr/feed/",
	"https://www.mothersblog.grhttps://www.mothersblog.gr/content?format=feed",
	"https://banks.com.gr/feed/",
	"https://newpost.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fnewpost.gr%2F&format=xml",
	"https://afteroffice.gr/feed/",
	"https://reporternews.gr/feed/",
	"https://www.e-vima.gr/feed/",
	"https://www.halkidikimaps.gr/feed/",
	"https://www.karpathiakanea.gr/feed/",
	"https://akromolio.gr/feed/",
	"https://www.athenstransport.com/feed/",
	"https://rethemnosnews.gr/rss.xml",
	"https://www.elassonanews.gr/feed/",
	"https://www.autogreeknews.gr/home/feed",
	"https://www.oraiokastro24.gr/feed/",
	"https://ka-business.gr/feed/",
	"https://www.kifisianews.gr/feed/",
	"https://travel.mykonosticker.com/feed/",
	"https://www.enikonomia.gr/feed/",
	"https://www.timed.gr/feed/",
	"https://www.all4mama.gr/feed/",
	"https://www.simpleradio.gr/feed/",
	"https://www.lakonikos.gr/?format=feed&type=rss",
	"https://www.lifo.gr/newsfeed",
	"https://thepressproject.gr/feed/",
	"https://www.4troxoi.gr/feed/",
	"https://www.kalavrytanews.com/feeds/posts/default",
	"https://www.newsitamea.gr/feed/",
	"https://reportplus.gr/feed/",
	"https://ontimenews.gr/feed/",
	"https://www.trifilara.gr/feed/",
	"https://iliapress.gr/?format=feed&type=rss",
	"https://azinlikca1.net/feed",
	"https://sfedona.gr/feed/",
	"https://kosmospierias.gr/feed/",
	"https://tagnews.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Ftagnews.gr%2F&format=xml",
	"https://energypress.eu/feed/",
	"https://www.ele.gr/?feed=rss2",
	"https://kyvernisi.com/feed/",
	"https://www.dramini.gr/?feed=rss2",
	"https://myk.gr/index.php/feed/",
	"https://www.lefkadaweb.gr/feed/",
	"https://culpanews.gr/feed/",
	"https://www.epirus-tv-news.gr/feeds/posts/default",
	"https://olympianews.gr/feed/",
	"https://www.economix.gr/feed/",
	"https://kritikoipalmoi-press.blogspot.com/feeds/posts/default",
	"https://www.eurohoops.net/feed/",
	"https://www.bestnews.gr/feed/",
	"https://bikeit.gr/?format=feed&type=rss",
	"https://www.gigafm.gr/feed/",
	"https://rp.gr/feed/",
	"https://acheloostvnews.gr/feed/",
	"https://fylakti.com/index.php?format=feed&type=rss",
	"https://tecky.eu/feed/",
	"https://www.timesnews.gr/feed/",
	"https://pameevro.gr/feed/",
	"https://xanthidaily.gr/feed/",
	"https://gonews.gr/feed/",
	"https://indexanthi.gr/feed/",
	"https://www.isalos.net/feed/",
	"https://stigmafm.gr/feed/",
	"https://elladatwra.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Felladatwra.gr%2F&format=xml",
	"https://www.newsvoice.gr/feed/",
	"https://imathiotis.gr/feed/",
	"https://patrainews.gr/feed/",
	"https://broadcastnews.gr/feed/",
	"https://seliniotikanea.gr/feed/",
	"https://kartaygeias.net/feed/",
	"https://radionews.live/feed/",
	"https://corfuvoice.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fcorfuvoice.gr%2F&format=xml",
	"https://www.mag24.gr/feed/",
	"https://www.cretanmagazine.gr/feed/",
	"https://ereporter.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fereporter.gr%2F&format=xml",
	"https://elaiaskarpos.gr/feed/",
	"https://inefan.gr/feed/",
	"https://marathonnews.gr/feed/",
	"https://parapolitikaargolida.gr/feed/",
	"https://www.ieidiseis.gr/news?format=feed",
	"http://www.eviatopblog.gr/feeds/posts/default",
	"https://odiavitismou.gr/feed/",
	"https://e-thessalia.gr/feed/",
	"https://moneyreview.grhttps://www.moneyreview.gr/newsfeed/",
	"https://www.culturenow.gr/feed/",
	"https://www.estianews.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.estianews.gr%2F&format=xml",
	"http://feeds.feedburner.com/diorismos/newsroom",
	"http://www.thetravelbook.gr/feed/",
	"https://dytikesmaties.gr/feed/",
	"https://arxon.gr/feed/",
	"https://www.zougla.gr/rss",
	"https://valueforlife.gr/feed/",
	"https://doriforiki.forumgreek.com/feed/?f=82",
	"https://www.verginanews.gr/feed/",
	"https://www.agon.gr/feed/",
	"https://fouit.gr/feed/",
	"https://doxthi.gr/feed/",
	"https://farmportal.grhttps://www.farmportal.gr/rss.xml",
	"https://www.infokids.gr/feed/",
	"https://www.alexandriamou.gr/?format=feed&type=rss",
	"https://travelpeloponnisos.gr/feed/",
	"https://www.in2life.gr/rss",
	"https://tomorrownews.gr/?format=feed&type=rss",
	"https://tranzistor1003.gr/feed/",
	"https://aquariusfm.gr/feed/",
	"https://www.koinignomi.gr/rss.xml",
	"https://nownews.gr/feed/",
	"https://www.achaiavoice.gr/feed/",
	"https://kosnews24.gr/?format=feed&type=rss",
	"https://typoskifissias.gr/?format=feed&type=rss",
	"https://goholidays.gr/feed/",
	"https://www.cna.gr/feed/",
	"https://travelthessaly.gr/feed/",
	"https://pharmamanage.gr/index.php?format=feed&type=rss",
	"https://trikalalife.gr/feed/",
	"https://glykouli.gr/feed/",
	"https://moschatomag.com/feed/",
	"https://pulsemag.gr/?feed=rss2",
	"https://www.karditsalive.net/?format=feed&type=rss",
	"https://trikalaenimerosi.gr/rss?projection=1095",
	"https://rodosinfonews.gr/feed/",
	"https://amarysianotia.gr/feed/",
	"https://armynews.gr/?feed=rss2",
	"https://www.enimerosi24.gr/feed/",
	"https://greveniotisa.gr/feed/",
	"https://proini.news/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fproini.news%2F&format=xml",
	"https://iator.grhttps://www.iator.gr/2009/03/15/feeding-and-canser-of-the-breast/",
	"https://www.ihunt.gr/feed/",
	"https://tomanifesto.gr/feed/",
	"https://pressone.gr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fpressone.gr%2F&format=xml",
	"https://www.e-volos.gr/feed/",
	"https://newsproject.gr/?format=feed&type=rss",
	"https://symmaxiagiatinellada.gr/index.php?format=feed&type=rss",
	"https://www.thriassio.gr/feed/",
	"https://www.ota24.gr/feed/",
	"https://www.startmediacorfu.gr/feed/",
	"https://otanews.gr/feed/",
	"https://tv10.gr/feed/",
	"https://www.rhodes.com.gr/feed/",
	"https://goaltime.gr/feed/",
	"https://www.pepper966.gr/feed/",
	"https://flamis.gr/feed/",
	"https://crimi.gr/feed/",
	"https://gocar.grhttps://www.gocar.gr/news/feed/",
	"https://detoxnews.grhttps://detoxnews.gr/sitemap.xml",
	"https://gosports.gr/feed/",
	"https://mileikanea.gr/?format=feed&type=rss",
	"https://stalanews.gr/feed/",
	"https://www.synorafm.gr/feed/",
	"https://xronikadramas.gr/feed/",
	"https://sportsfan.gr/feed/",
	"https://theartnewspaper.gr/feed/",
	"https://primenews.press/feed",
	"https://aristeia.online/feed/",
	"https://notianea.gr/feed/",
	"https://www.prevezatoday.gr/feed/",
	"https://www.gameslife.gr/feed",
	"https://evivanews.gr/feed/",
	"https://aluminium.gr/feed/",
	"https://www.iatronet.gr/entries/79/iatronetgr-rss-feeds.html",
	"https://www.newsvolos.com/feed/",
	"https://cretapress.gr/feed/",
	"https://www.ithessaly.gr/feeds/posts/default",
	"https://a-sports.gr/rss_feeds.php",
	"https://www.motori.gr/feed/",
	"https://www.prokirixi.gr/feed/",
	"https://notosport.eleftheriaonline.gr/?format=feed&type=rss",
	"https://maxitisthrakis.blogspot.com/feeds/posts/default",
	"https://www.alphafm.gr/feed/",
}

// ListenGroup struct.
type ListenGroup struct {
	ctx         context.Context
	log         *zap.SugaredLogger
	kafkaClient *kafka.KafkaGoClient
	errChan     chan error
}

// Close closes the kafka client.
func (worker *ListenGroup) Close() {
	worker.kafkaClient.Close()
}

// Procuce writes a new message to the kafka topic.
func (worker *ListenGroup) Produce(msg kaf.Message) {
	err := worker.kafkaClient.Producer.WriteMessages(worker.ctx, msg)
	if err != nil {
		worker.log.Errorf("[SVC-FEEDS] Failed to write messages to kafka: %s", err.Error())
		worker.errChan <- errors.Wrap(err, "failed to write messages to kafka")
	}
}

// NewListenGroup implements a new ListenGroup struct.
func NewListenGroup(
	log *zap.SugaredLogger,
	kafkaClient *kafka.KafkaGoClient,
	errChan chan error,
) *ListenGroup {
	return &ListenGroup{
		context.Background(),
		log,
		kafkaClient,
		errChan,
	}
}

func main() {
	// ============================================================
	// Read Config
	// ============================================================
	cfg := config.NewConfig()

	// Read config from env variables
	err := envconfig.Process("", cfg)
	if err != nil {
		panic(err)
	}

	// ============================================================
	// Set Logger
	// ============================================================
	log := logger.NewLogger(cfg.Env, cfg.Log.Level, cfg.Log.Path)
	log.Info("[SVC-FEEDS] Starting")

	// ============================================================
	// Mongo
	// ============================================================
	log.Info("[SVC-FEEDS] Initialize Mongo")
	dbConn, err := db.NewMongoDB(cfg.Mongo.URL, cfg.Mongo.Path, cfg.Mongo.DialTimeout)
	if err != nil {
		log.Fatalf("[SVC-FEEDS] Register DB: %v", err)
	}
	log.Info("[SVC-FEEDS] Connected to Mongo")
	defer dbConn.Close()

	// ============================================================
	// Redis
	// ============================================================
	rdb, err := redis.NewRedisClient(context.Background(), cfg.GetRedisURL(), "")
	if err != nil {
		log.Fatalf("[SVC-FEEDS] Error connecting to Redis: %s", err.Error())
	}
	log.Info("[SVC-FEEDS] Connected to Redis")
	defer rdb.Close()

	// ============================================================
	// Kafka
	// ============================================================
	// create an error channel to forward errors
	kafkaChan := make(chan error, 1)

	// create a reader/writer kafka connection
	kafkaGoClient := kafka.NewGoClient(
		false, true,
		[]string{cfg.Kafka.Broker},
		"",
		"",
		cfg.Kafka.WorkerTopic,
		cfg.Kafka.ConsumerGroupWorker,
		false,
	)

	// create a new worker
	worker := NewListenGroup(log, kafkaGoClient, kafkaChan)
	// close connections on exit
	defer worker.Close()

	// ============================================================
	// Proxy HTTP Client
	// ============================================================
	proxy, _ := url.Parse("socks5://0.0.0.0:9201")
	proxyClient := &http.Client{Transport: &http.Transport{Proxy: http.ProxyURL(proxy)}}

	// ============================================================
	// Prometheus
	// ============================================================
	// Create a registry and a web server for prometheus metrics
	registry := prometheus.NewRegistry()

	// ============================================================
	// Get feeds list
	feeds, err := feed.GetTargets(context.Background(), dbConn, feed.Limit(3000), feed.Lang("EL"), feed.StreamType("rss"))
	if err != nil {
		log.Fatalf("[SVC-FEEDS] error getting feeds list: %v", err)
	}

	log.Infof("[SVC-FEEDS] Loaded feeds: %d", len(feeds.Data))

	// ============================================================
	// Ticker
	// ============================================================
	done := make(chan bool, 1)
	defer close(done)

	go func(log *zap.SugaredLogger, worker *ListenGroup, rdb *redis.RedisClient, proxyClient *http.Client, done chan bool, targets []*feed.Feed, init bool) {
		c := chunks(targets, 100)
		for _, v := range c {
			ticker := NewTicker(log, worker, rdb, proxyClient, done, v, init)
			go ticker.Tick()
			time.Sleep(time.Minute / 2)
		}
	}(log, worker, rdb, proxyClient, done, feeds.Data, cfg.RSSStreamer.Init)

	// ============================================================
	// Set Channels
	// ============================================================
	// Make a channel to listen for errors coming from the listener. Use a
	// buffered channel so the goroutine can exit if we don't collect this error.
	errSingals := make(chan error, 1)

	// api will be our http.Server
	promHandler := http.Server{
		Addr:           cfg.GetPrometheusURL(),
		Handler:        promhttp.HandlerFor(registry, promhttp.HandlerOpts{}), // api(cfg.Log.Debug, registry),
		ReadTimeout:    cfg.Prometheus.ReadTimeout,
		WriteTimeout:   cfg.Prometheus.WriteTimeout,
		MaxHeaderBytes: 1 << 20,
	}

	// Start the service listening for requests.
	log.Info("[SVC-FEEDS] Ready to start")
	go func() {
		log.Infof("[SVC-FEEDS] Starting prometheus web server listening %s", cfg.GetPrometheusURL())
		errSingals <- promHandler.ListenAndServe()
	}()

	// ============================================================
	// Termination
	// ============================================================
	// Listen for os signals
	osSignals := make(chan os.Signal, 1)
	signal.Notify(osSignals, syscall.SIGINT, syscall.SIGTERM)

	// =========================================================================
	// Stop API Service
	// Blocking main and waiting for shutdown.
	select {
	case err := <-kafkaChan:
		// Ignore the Error
		log.Errorf("[SVC-FEEDS] Error from kafka: %v", err)

	case err := <-errSingals:
		// Got Error from stream
		log.Errorf("[SVC-FEEDS] Error while streaming tweets: %s", err.Error())
		os.Exit(1)

	case s := <-osSignals:
		log.Debugf("[SVC-FEEDS] Listen shutdown signal: %s", s)

		// Asking prometheus to shutdown and load shed.
		if err := promHandler.Shutdown(context.Background()); err != nil {
			log.Errorf("[SVC-COMPARE] Graceful shutdown did not complete in %v: %v", cfg.Prometheus.ShutdownTimeout, err)
			if err := promHandler.Close(); err != nil {
				log.Fatalf("[SVC-COMPARE] Could not stop http server: %v", err)
			}
		}
	}
}

func chunks(feeds []*feed.Feed, size int) [][]*feed.Feed {
	var chunks [][]*feed.Feed
	for i := 0; i < len(feeds); i += size {
		d := i + size
		if d > len(feeds) {
			d = len(feeds)
		}
		chunks = append(chunks, feeds[i:d])
	}
	return chunks
}

// getIds list to listen
func getIds(feeds []*feed.Feed) []string {
	twitterIDs := make([]string, 0)
	for _, f := range feeds {
		if f.TwitterIDStr != "" {
			twitterIDs = append(twitterIDs, f.TwitterIDStr)
		} else {
			twitterIDs = append(twitterIDs,
				strconv.FormatInt(f.TwitterID, 10))
		}
	}
	return twitterIDs
}

// getUsernames list to listen
func getUsernames(feeds []*feed.Feed) []string {
	twitterUsernames := make([]string, 0)
	for _, f := range feeds {
		if f.ScreenName != "" {
			twitterUsernames = append(twitterUsernames, f.ScreenName)
		}
	}
	return twitterUsernames
}

func getUserNameFromTweet(authorId string, users []*twitter.User) string {
	for _, v := range users {
		if v.ID == authorId {
			return v.UserName
		}
	}
	return ""
}
